cassandra:
  image: cassandra:3.11.4
  container_name: cassandra
  env_file:
    - cassandra/cassandra.env
  ports:
    - "9042:9042"
  environment:
    - "MAX_HEAP_SIZE=256M"
    - "HEAP_NEWSIZE=128M"
  restart: always
  volumes:
    - "./cassandra-init.sh:/cassandra-init.sh"
  command: "sh /cassandra-init.sh"